app_name: swagger-go
version: 0.1.2
image_name: registry.cn-shanghai.aliyuncs.com/d2jvkpn/swagger-go
repository: git@github.com:d2jvkpn/swagger-go.git

# -config=configs/local.yaml::swagger
swagger:
  title: "TODO"
  base_path: "TODO"
  accounts:
  - { username: hello, password: world }
