app_name: swagger-go
app_version: 0.1.0
# image_name: registry.cn-shanghai.aliyuncs.com/d2jvkpn/swagger-go
image_name: app-swagger
repository: git@github.com:d2jvkpn/swagger-go.git

# -config=configs/local.yaml
swagger:
  title: "TODO"
  base_path: "TODO"
  accounts:
  - { name: "accounts", password: "password" }
